---

- name: install ambari-agent
  yum: name=ambari-agent state=latest

#- name: Configure ambari-server hostname in ambari-agent configuration
#  lineinfile: dest=/etc/ambari-agent/conf/ambari-agent.ini regexp=^.*hostname=.*$ line=hostname="{{ item }}" backup=yes
#  with_items:
#    - "{{ ambari_server }}"

- name: Set the Ambari Server in the agent configuration
  lineinfile:
    path: /etc/ambari-agent/conf/ambari-agent.ini
    regexp: "^hostname="
    line: "hostname={{ hostvars[groups['master']|first]['ansible_fqdn'] }}"
    state: present

### The following is done on Python >= 2.7 to prevent issues with the latest Python libraries rejecting lower TLS protocols
- name: Configure the Ambari Agents to use TLS 1.2
  ini_file:
    path: /etc/ambari-agent/conf/ambari-agent.ini
    create: no
    section: "security"
    option: "force_https_protocol"
    value: "PROTOCOL_TLSv1_2"
    state: present
  when: (ansible_python_version is version_compare('2.7.9', '>=') and ansible_os_family|lower == "debian") or
        (ansible_python_version is version_compare('2.7', '>=') and ((ansible_os_family|lower == "redhat" and ansible_distribution_major_version|int >= 7) or
                                                                     (ansible_os_family|lower == "suse" and ansible_distribution_major_version|int >= 12) or
                                                                     (ansible_os_family|lower == "redhat" and ansible_distribution|lower == "amazon")))


- name: Ensure ambari-agent is running and enabled
  service: name=ambari-agent state=restarted enabled=yes

- name : wait for agent to register
  command : sleep 10

